services:

  raulex-lib:
    build: ./raulex-lib
    volumes:
      - ./raulex-lib/src:/usr/app/src
    environment:
      - REDIS_URL=redis://redis-storage
    ports:
      - 8000:8000
    networks:
      - backend

  redis-storage:
    build: ./redis-storage
    volumes:
      - ./redis-storage/data:/data
    networks:
      - backend

  mongo-db:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    networks:
      - backend
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo-db:27017/

networks:
  backend:
